title: Axe API
description: Next Generation Rest API Framework. In this blog you can find everything about Axe API.
keywords: axe api, rest api, api development, restful, nodejs, expressjs, knexjs, mysql, postgres
author: Özgür Adem Işıklı
footer: Axe API - 2023
hostname: https://blog.axe-api.com
